/* eslint-disable @typescript-eslint/no-unused-vars */

import {registerPaymentMethod, registerExpressPaymentMethod} from '@woocommerce/blocks-registry';
import AlipayPaymentMethod from './alipay';
import AmazonPay from './amazonpay';
import AmazonPayExpress from './amazonpay/express';
import Bancontact from './bancontact';
import RatepayDirectDebit from './ratepay/direct-debit';
import RatepayOpenInvoice from './ratepay/open-invoice';
import RatepayInstallments from './ratepay/installments';
import CreditCard from './credit-card';
import Przelewy24 from './przelewy24';
import PrePayment from './pre-payment';
import SafeInvoice from './safe-invoice';
import Invoice from './invoice';
import Eps from './eps';
import Ideal from './ideal';
import Paypal from './paypal';
import PaypalV2 from './paypalv2';
import PaypalV2Express from './paypalv2/express';
import KlarnaInvoice from './klarna/invoice';
import KlarnaInstallments from './klarna/installments';
import KlarnaSofort from './klarna/sofort';
import PaylaSecuredInvoice from './payla/secured-invoice';
import PaylaSecuredInstallment from './payla/secured-installment';
import PaylaSecuredDirectDebit from './payla/secured-direct-debit';
import SepaDirectDebit from './sepa';

registerPaymentMethod(AlipayPaymentMethod);
registerPaymentMethod(AmazonPay);
registerExpressPaymentMethod(AmazonPayExpress);
registerPaymentMethod(Bancontact);
registerPaymentMethod(Przelewy24);
registerPaymentMethod(RatepayDirectDebit);
registerPaymentMethod(RatepayOpenInvoice);
registerPaymentMethod(RatepayInstallments);
registerPaymentMethod(CreditCard);
registerPaymentMethod(PrePayment);
registerPaymentMethod(SafeInvoice);
registerPaymentMethod(Invoice);
registerPaymentMethod(Eps);
registerPaymentMethod(Ideal);
registerPaymentMethod(Paypal);
registerPaymentMethod(PaypalV2);
registerExpressPaymentMethod(PaypalV2Express);
registerPaymentMethod(KlarnaInvoice);
registerPaymentMethod(KlarnaInstallments);
registerPaymentMethod(KlarnaSofort);
registerPaymentMethod(PaylaSecuredInvoice);
registerPaymentMethod(PaylaSecuredInstallment);
registerPaymentMethod(PaylaSecuredDirectDebit);
registerPaymentMethod(SepaDirectDebit);
