<?php

namespace Payone\Gateway;

use Automattic\WooCommerce\Blocks\Payments\Integrations\AbstractPaymentMethodType;
use Automattic\WooCommerce\StoreApi\Payments\PaymentContext;
use Payone\Plugin;

class PayoneBlocksSupport extends AbstractPaymentMethodType {
	protected $name = 'payone';

	/**
	 * @var CreditCard|null
	 */
	private $creditCardGateway = null;

	/**
	 * @var SecuredInvoice|null
	 */
	private $paylaSecuredInvoiceGateway = null;

	/**
	 * @var SecuredInstallment|null
	 */
	private $paylaSecuredInstallmentGateway = null;

	/**
	 * @var SecuredDirectDebit|null
	 */
	private $paylaSecuredDirectDebitGateway = null;

	/**
	 * @var RatepayOpenInvoice|null
	 */
	private $ratepayOpenInvoiceGateway = null;

	/**
	 * @var RatepayInstallments|null
	 */
	private $ratepayInstallmentsGateway = null;

	/**
	 * @var RatepayDirectDebit|null
	 */
	private $ratepayDirectDebitGateway = null;

	/**
	 * @var PayPalV2Express|null
	 */
	private $paypalV2ExpressGateway = null;

	/**
	 * @var AmazonPay|null
	 */
	private $amazonPayGateway = null;

	/**
	 * @var AmazonPayExpress|null
	 */
	private $amazonPayExpressGateway = null;

	public function initialize() {
		add_action( 'wp_enqueue_scripts', [ $this, 'client_styles' ] );
		add_action( 'woocommerce_rest_checkout_process_payment_with_context', [
			$this,
			'add_payment_request_order_meta'
		], 8, 2 );

		// Gateways are now lazy-loaded via getter methods when needed
	}

	public function is_active() {
		return parent::is_active(); // TODO: Change the autogenerated stub
	}

	/**
	 * Lazy load gateways - initialize only when needed
	 *
	 * @return CreditCard|null Returns null if gateway instantiation fails
	 */
	private function getCreditCardGateway() {
		if ( $this->creditCardGateway === null ) {
			try {
				$this->creditCardGateway = new CreditCard();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate CreditCard Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->creditCardGateway;
	}

	/**
	 * @return SecuredInvoice|null Returns null if gateway instantiation fails
	 */
	private function getPaylaSecuredInvoiceGateway() {
		if ( $this->paylaSecuredInvoiceGateway === null ) {
			try {
				$this->paylaSecuredInvoiceGateway = new SecuredInvoice();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate SecuredInvoice Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->paylaSecuredInvoiceGateway;
	}

	/**
	 * @return SecuredInstallment|null Returns null if gateway instantiation fails
	 */
	private function getPaylaSecuredInstallmentGateway() {
		if ( $this->paylaSecuredInstallmentGateway === null ) {
			try {
				$this->paylaSecuredInstallmentGateway = new SecuredInstallment();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate SecuredInstallment Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->paylaSecuredInstallmentGateway;
	}

	/**
	 * @return SecuredDirectDebit|null Returns null if gateway instantiation fails
	 */
	private function getPaylaSecuredDirectDebitGateway() {
		if ( $this->paylaSecuredDirectDebitGateway === null ) {
			try {
				$this->paylaSecuredDirectDebitGateway = new SecuredDirectDebit();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate SecuredDirectDebit Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->paylaSecuredDirectDebitGateway;
	}

	/**
	 * @return RatepayOpenInvoice|null Returns null if gateway instantiation fails
	 */
	private function getRatepayOpenInvoiceGateway() {
		if ( $this->ratepayOpenInvoiceGateway === null ) {
			try {
				$this->ratepayOpenInvoiceGateway = new RatepayOpenInvoice();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate RatepayOpenInvoice Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->ratepayOpenInvoiceGateway;
	}

	/**
	 * @return RatepayInstallments|null Returns null if gateway instantiation fails
	 */
	private function getRatepayInstallmentsGateway() {
		if ( $this->ratepayInstallmentsGateway === null ) {
			try {
				$this->ratepayInstallmentsGateway = new RatepayInstallments();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate RatepayInstallments Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->ratepayInstallmentsGateway;
	}

	/**
	 * @return RatepayDirectDebit|null Returns null if gateway instantiation fails
	 */
	private function getRatepayDirectDebitGateway() {
		if ( $this->ratepayDirectDebitGateway === null ) {
			try {
				$this->ratepayDirectDebitGateway = new RatepayDirectDebit();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate RatepayDirectDebit Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->ratepayDirectDebitGateway;
	}

	/**
	 * @return PayPalV2Express|null Returns null if gateway instantiation fails
	 */
	private function getPaypalV2ExpressGateway() {
		if ( $this->paypalV2ExpressGateway === null ) {
			try {
				$this->paypalV2ExpressGateway = new PayPalV2Express();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate PayPalV2Express Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->paypalV2ExpressGateway;
	}

	/**
	 * @return AmazonPay|null Returns null if gateway instantiation fails
	 */
	private function getAmazonPayGateway() {
		if ( $this->amazonPayGateway === null ) {
			try {
				$this->amazonPayGateway = new AmazonPay();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate AmazonPay Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->amazonPayGateway;
	}

	/**
	 * @return AmazonPayExpress|null Returns null if gateway instantiation fails
	 */
	private function getAmazonPayExpressGateway() {
		if ( $this->amazonPayExpressGateway === null ) {
			try {
				$this->amazonPayExpressGateway = new AmazonPayExpress();
			} catch ( \Exception $e ) {
				error_log( 'PAYONE: Failed to instantiate AmazonPayExpress Gateway: ' . $e->getMessage() );
				return null;
			}
		}
		return $this->amazonPayExpressGateway;
	}

	/**
	 * In this function you should register your payment method scripts (using wp_register_script) and then return the
	 * script handles you registered with. This will be used to add your payment method as a dependency of the checkout
	 * script and thus take sure of loading it correctly.
	 *
	 * @return string[]
	 */
	public function get_payment_method_script_handles() {
		$asset_path   = PAYONE_PLUGIN_URL . '/assets/build/index.asset.php';
		$version      = PAYONE_PLUGIN_VERSION;
		$dependencies = [];
		if ( file_exists( $asset_path ) ) {
			$asset        = require $asset_path;
			$version      = is_array( $asset ) && isset( $asset['version'] )
				? $asset['version']
				: $version;
			$dependencies = is_array( $asset ) && isset( $asset['dependencies'] )
				? $asset['dependencies']
				: $dependencies;
		}

		wp_register_script(
			'wc-payone-blocks-integration',
			PAYONE_PLUGIN_URL . '/assets/build/blocks.js',
			$dependencies,
			$version,
			true
		);

		wp_set_script_translations( 'wc-payone-blocks-integration', 'payone-woocommerce-3', PAYONE_PLUGIN_PATH . '/lang' );

		return [ 'wc-payone-blocks-integration' ];
	}

	/**
	 * Include this if your payment method has a script you only want to load in the editor context for the checkout
	 * block. Include here any script from get_payment_method_script_handles that is also needed in the admin.
	 *
	 * @return string[]
	 */
	public function get_payment_method_script_handles_for_admin() {
		return parent::get_payment_method_script_handles_for_admin(); // TODO: Change the autogenerated stub
	}

	/**
	 * You can return from this function an associative array of data you want to be exposed for your payment method
	 * client side. This data will be available client side via wc.wcSettings.getSetting. So for instance if you
	 * assigned stripe as the value of the name property for this class, client side you can access any data
	 * via: wc.wcSettings.getSetting( 'stripe_data' ). That would return an object matching the shape of the
	 * associative array you returned from this function.
	 *
	 * @return array
	 */
	public function get_payment_method_data() {
		$data = parent::get_payment_method_data();

		// Pass plugin URL to JavaScript for dynamic asset path construction
		$data['pluginUrl'] = PAYONE_PLUGIN_URL;

		$data['creditCardCheckRequestConfig'] = $this->get_credit_card_check_request();
		$data['payoneConfig']                 = $this->getCreditCardGateway()->javascript_payone_config();
		$data['cardTypes']                    = $this->get_card_types();
		$data['epsBankGroups']                = $this->get_eps_bank_groups();
		$data['idealBankGroups']              = $this->get_ideal_bank_groups();
		$data['ratepayCalculationUrl']        = Plugin::get_callback_url( [ 'type' => 'ajax-ratepay-calculate' ] );
		$data['klarnaStartSessionUrl']        = Plugin::get_callback_url( [ 'type' => 'ajax-klarna-start-session' ] );
		$data['sepaManageMandateUrl']         = Plugin::get_callback_url( [ 'type' => 'ajax-manage-mandate' ] );
		$data['paylaConfig']                  = [
			'environmentKey'                  => $this->getPaylaSecuredInvoiceGateway()->get_environment(),
			'cssUrl'                          => $this->getPaylaSecuredInvoiceGateway()->get_client_css(),
			'jsUrl'                           => $this->getPaylaSecuredInvoiceGateway()->get_client_js(),
			'tokenSecuredInvoice'             => $this->getPaylaSecuredInvoiceGateway()->get_snippet_token(),
			'tokenSecuredInstallment'         => $this->getPaylaSecuredInstallmentGateway()->get_snippet_token(),
			'tokenSecuredDirectDebit'         => $this->getPaylaSecuredDirectDebitGateway()->get_snippet_token(),
			'urlSecuredInstallment'           => Plugin::get_callback_url( [ 'type' => 'ajax-secured-installment-options' ] ),
			'allowDifferentShippingAddress'   => [
                'payone_secured_invoice'      => $this->getPaylaSecuredInvoiceGateway()->get_option( 'allow_different_shopping_address', 'no' ) === 'yes',
                'payone_secured_installment'  => $this->getPaylaSecuredInstallmentGateway()->get_option( 'allow_different_shopping_address', 'no' ) === 'yes',
                'payone_secured_direct_debit' => $this->getPaylaSecuredDirectDebitGateway()->get_option( 'allow_different_shopping_address', 'no' ) === 'yes',
            ],
		];
		$data['ratepayConfig']                = [
			'allowDifferentShippingAddress'   => [
                'payone_ratepay_open_invoice'  => $this->getRatepayOpenInvoiceGateway()->get_option( 'allow_different_shopping_address', 'no' ) === 'yes',
                'payone_ratepay_installments'  => $this->getRatepayInstallmentsGateway()->get_option( 'allow_different_shopping_address', 'no' ) === 'yes',
                'payone_ratepay_direct_debit'  => $this->getRatepayDirectDebitGateway()->get_option( 'allow_different_shopping_address', 'no' ) === 'yes',
            ],
		];
        $data['paypalExpressConfig']          = [
            'jsUrl' => 'https://www.paypal.com/sdk/js?client-id='.$this->getPaypalV2ExpressGateway()->get_payone_client_id().'&merchant-id='.$this->getPaypalV2ExpressGateway()->get_payone_merchant_id().'&currency=EUR&intent=authorize&locale=de_DE&commit=false&vault=false&disable-funding=card,sepa,bancontact'.( $this->getPaypalV2ExpressGateway()->get_allow_paylater() ? '&enable-funding=paylater' : ''),
            'callbackUrl' => Plugin::get_callback_url( [ 'type' => 'paypalv2', 'a' => 'express-set-checkout' ] ),
            'redirectUrl' => Plugin::get_callback_url( [ 'type' => 'paypalv2', 'a' => 'express-get-checkout' ] ),
            'isAvailable' => $this->getPaypalV2ExpressGateway()->is_available(),
        ];
        $data['paypalConfig']                 = [
            'isAvailable' => Plugin::find_gateway(PayPal::GATEWAY_ID)->is_available(),
        ];
		$data['amazonPayConfig']              = [
			'sdkUrl'                      => 'https://static-eu.payments-amazon.com/checkout.js',
			'merchantId'                  => $this->getAmazonPayGateway()->get_amazon_merchant_id(),
			'publicKeyId'                 => AmazonPay::PUBLIC_KEY_ID,
			'ledgerCurrency'              => get_woocommerce_currency(),
			'checkoutLanguage'            => get_locale(),
			'buttonColor'                 => $this->getAmazonPayGateway()->get_button_color(),
			'productType'                 => 'PayAndShip',
			'sandbox'                     => $this->getAmazonPayGateway()->get_mode() === 'test',
			'isAvailable'                 => $this->getAmazonPayGateway()->is_available(),
			'isExpressAvailable'          => $this->getAmazonPayExpressGateway()->is_available(),
			'createSessionUrl'            => Plugin::get_callback_url( [ 'type' => 'amazonpay', 'a' => 'blocks-create-session' ] ),
			'createSessionExpressUrl'     => Plugin::get_callback_url( [ 'type' => 'amazonpay', 'a' => 'blocks-express-create-session' ] ),
			'description'                 => $this->getAmazonPayGateway()->get_option( 'description' ),
		];

		// TODO: installmentMonthOptions müssen hier befüllt werden
		$data['installmentMonthOptions'] = [
			'0',
			'3',
			'6',
			'12',
			'24',
		];

		return $data;
	}

	private function get_card_types() {
		$gateway = $this->getCreditCardGateway();
		if ( $gateway === null ) {
			return [];
		}

		$brands = $gateway->get_option( 'cc_brands' );
		if ( ! is_array( $brands ) ) {
			return [];
		}

		return array_map(
			function ( $brand ) use ( $gateway ) {
				return [
					'value' => $brand,
					'title' => $gateway->get_option( 'cc_brand_label_' . $brand ),
				];
			},
			$brands
		);
	}

	private function get_credit_card_check_request() {
		$gateway = $this->getCreditCardGateway();
		if ( $gateway === null ) {
			return [];
		}

		$payoneRequestOptions = [
			'mode'          => esc_attr( $gateway->get_mode() ),
			'merchant_id'   => esc_attr( $gateway->get_merchant_id() ),
			'account_id'    => esc_attr( $gateway->get_account_id() ),
			'portal_id'     => esc_attr( $gateway->get_portal_id() ),
			'key'           => esc_attr( $gateway->get_key() ),
			'request'       => 'creditcardcheck',
			'responsetype'  => 'JSON',
			'encoding'      => 'UTF-8',
			'storecarddata' => 'yes',
		];

		return array_merge( $payoneRequestOptions, [
			'hash' => $gateway->calculate_hash( $payoneRequestOptions )
		] );
	}

	// TODO: Derzeit einfach kopiert aus Gateway/Eps.php
	private function get_eps_bank_groups() {
		return [
			'ARZ_OAB'       => 'Apothekerbank',
			'ARZ_BAF'       => 'Ärztebank',
			'BA_AUS'        => 'Bank Austria',
			'ARZ_BCS'       => 'Bankhaus Carl Spängler & Co.AG',
			'EPS_SCHEL'     => 'Bankhaus Schelhammer & Schattera AG',
			'BAWAG_PSK'     => 'BAWAG P.S.K. AG',
			'BAWAG_ESY'     => 'Easybank AG',
			'SPARDAT_EBS'   => 'Erste Bank und Sparkassen',
			'ARZ_HAA'       => 'Hypo Alpe-Adria-Bank International AG',
			'ARZ_VLH'       => 'Hypo Landesbank Vorarlberg',
			'HRAC_OOS'      => 'HYPO Oberösterreich,Salzburg,Steiermark',
			'ARZ_HTB'       => 'Hypo Tirol Bank AG',
			'EPS_OBAG'      => 'Oberbank AG',
			'RAC_RAC'       => 'Raiffeisen Bankengruppe Österreich',
			'EPS_SCHOELLER' => 'Schoellerbank AG',
			'ARZ_OVB'       => 'Volksbank Gruppe',
			'EPS_VRBB'      => 'VR-Bank Braunau',
			'EPS_AAB'       => 'Austrian Anadi Bank AG',
			'EPS_BKS'       => 'BKS Bank AG',
			'EPS_BKB'       => 'Brüll Kallmus Bank AG',
			'EPS_VLB'       => 'BTV VIER LÄNDER BANK',
			'EPS_CBGG'      => 'Capital Bank Grawe Gruppe AG',
			'EPS_DB'        => 'Dolomitenbank',
			'EPS_NOELB'     => 'HYPO NOE Landesbank AG',
			'EPS_HBL'       => 'HYPO-BANK BURGENLAND Aktiengesellschaft',
			'EPS_MFB'       => 'Marchfelder Bank',
			'EPS_SPDBW'     => 'Sparda Bank Wien',
			'EPS_SPDBA'     => 'SPARDA-BANK AUSTRIA',
			'EPS_VKB'       => 'Volkskreditbank AG',
		];
	}

	private function get_ideal_bank_groups() {
		return [
			'ABN_AMRO_BANK'         => 'ABN Amro',
			'ASN_BANK'              => 'ASN Bank',
			'BUNQ_BANK'             => 'Bunq',
			'ING_BANK'              => 'ING Bank',
			'KNAB_BANK'             => 'Knab',
			'RABOBANK'              => 'Rabobank',
			'REVOLUT'               => 'Revolut',
			'SNS_BANK'              => 'SNS Bank',
			'SNS_REGIO_BANK'        => 'Regio Bank',
			'TRIODOS_BANK'          => 'Triodos Bank',
			'VAN_LANSCHOT_BANKIERS' => 'van Lanschot',
			'YOURSAFE'              => 'Yoursafe B.V',
		];
	}

	public function client_styles() {
		wp_register_style(
			'payone_client_styles',
			PAYONE_PLUGIN_URL . '/assets/css/client.css',
			[],
			PAYONE_PLUGIN_VERSION
		);

		if ( ! is_admin() ) {
			wp_enqueue_style( 'payone_client_styles' );
		}
	}

	public function add_payment_request_order_meta( PaymentContext $context ) {
		$data = $context->payment_data;
		if ( $context->payment_type === RatepayDirectDebit::GATEWAY_ID ) {
			$_POST['ratepay_direct_debit_iban']     = $data['ratepay_direct_debit_iban'];
			$_POST['ratepay_direct_debit_birthday'] = $data['ratepay_direct_debit_birthday'];
		}

		if ( $context->payment_type === RatepayOpenInvoice::GATEWAY_ID ) {
			$_POST['ratepay_direct_debit_birthday'] = $data['ratepay_direct_debit_birthday'];
		}

		if ( $context->payment_type === CreditCard::GATEWAY_ID ) {
			$_POST['card_pseudopan'] = $data['card_pseudopan'];
			$_POST['card_holder']    = $data['card_holder'];
		}

		if ( $context->payment_type === Eps::GATEWAY_ID ) {
			$_POST['bankgrouptype'] = $data['bankgrouptype'];
		}

		if ( $context->payment_type === AmazonPay::GATEWAY_ID ) {
			if ( isset( $data['amazonpay_workorderid'] ) ) {
				Plugin::set_session_value( AmazonPayBase::SESSION_KEY_WORKORDERID, $data['amazonpay_workorderid'] );
			}
		}

		if ( $context->payment_type === AmazonPayExpress::GATEWAY_ID ) {
			if ( isset( $data['amazonpay_workorderid'] ) ) {
				Plugin::set_session_value( AmazonPayBase::SESSION_KEY_WORKORDERID, $data['amazonpay_workorderid'] );
			}
			if ( isset( $data['amazonpay_express_used'] ) && $data['amazonpay_express_used'] ) {
				Plugin::set_session_value( AmazonPayExpress::SESSION_KEY_AMAZONPAY_EXPRESS_USED, true );
			}
		}
	}
}
